apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fusion-ext-system-bff.fullname" . }}-rbac
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fusion-ext-system-bff.labels" . | nindent 4 }}
data:
  rbac.yaml: |
    {{- .Files.Get "rbac.yaml" | nindent 4 }}
