{{- if and .Values.secret.create (or .Values.secret.apikeyHashedKeys .Values.secret.dbDsn) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fusion-ext-system-bff.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fusion-ext-system-bff.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secret.apikeyHashedKeys }}
  APIKEY_HASHED_KEYS: {{ .Values.secret.apikeyHashedKeys | quote }}
  {{- end }}
  {{- if .Values.secret.dbDsn }}
  DB_DSN: {{ .Values.secret.dbDsn | quote }}
  {{- end }}
{{- end }}
